name: Create Slides on Google Drive

on:
  workflow_dispatch:

jobs:
  send_slack_reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Upload file into Google Drive
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        FOLDER_ID: ${{ secrets.FOLDER_ID }}
      run: |
        python c:/Users/ihidalgo/Documents/git/Auto_Slides/script.py

    - name: Commit the changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: GitHub Action - Update presentation_links.json