
name: Weekly Slack Reminder

on:
  schedule:
    # Runs at 9:00 AM UTC every Friday
    - cron: '0 9 * * 5'
  workflow_dispatch:

jobs:
  send_slack_reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get the next Monday date
      id: get_date
      run: |
        output=$(python3 scripts/calculate_next_monday.py)
        echo "date=$output" >> $GITHUB_OUTPUT
    - name: Generate the presentation on Google Drive
      id: generate_presentation
      env:
        SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        FOLDER_ID: ${{ secrets.FOLDER_ID }}
      run: |
        output=$(python3 scripts/create_presentation.py --date ${{ steps.get_date.outputs.date }})
        echo "link=$output" >> $GITHUB_OUTPUT
    - name: Run Slack reminder script
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      run: |
        python scripts/slack_message.py --token $SLACK_TOKEN --channel $SLACK_CHANNEL --link ${{ steps.generate_presentation.outputs.link }}