
name: Weekly Slack Reminder

on:
  schedule:
    # Runs at 9:00 AM UTC every Friday
    - cron: '0 9 * * 5'
  workflow_dispatch:

jobs:
  send_slack_reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Slack reminder script
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLIDES_LINK: ${{ secrets.SLIDES_LINK }}
        SLIDES_NAME: ${{ secrets.SLIDES_NAME }}
      run: |
        python slack_message.py --token $SLACK_TOKEN --channel $SLACK_CHANNEL --link SLIDES_LINK --slide_name $SLIDES_NAME